name: Run

on:
  schedule:
    - cron: '42 1 * * *'
  workflow_dispatch:

jobs:
  roulette:
    runs-on: ubuntu-latest

    env:
      TG_API_ID: ${{ secrets.TG_API_ID }}
      TG_API_HASH: ${{ secrets.TG_API_HASH }}
      TG_SESSION: ${{ secrets.TG_SESSION }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install telethon

      - name: Run Script
        run: python main.py
